"""
prompt_template.py
------------------
Production-level Master Prompt Builder for the Grounded Medical Report
Intelligence System.

Design Goals:
  - Zero hallucination: LLM is constrained to provided context only
  - Temperature: 0.2 (set in grok_client.py)
  - Supports Patient Mode and Doctor/Clinical Mode
  - Supports multilingual output (English, Hindi, Telugu)
  - Always includes explainability note and safety disclaimer
"""

from typing import Literal

ModeType = Literal["patient", "doctor"]
LanguageType = Literal["English", "Hindi", "Telugu"]


def _format_structured_tests(tests: dict) -> str:
    """Format test results into a readable table for the prompt."""
    lines = []
    for test_name, data in tests.items():
        value  = data.get("value", "N/A")
        unit   = data.get("unit", "")
        status = data.get("status", "N/A")
        lines.append(f"  - {test_name}: {value} {unit}  [Status: {status}]")
    return "\n".join(lines) if lines else "  No tests provided."


def _format_panels(panels: list) -> str:
    """Format dynamic panels (from LLM extraction) into a structured table."""
    if not panels:
        return "  Not available."
    lines = []
    for panel in panels:
        lines.append(f"\n  [{panel.get('panel_name','General')}]")
        for t in panel.get("tests", []):
            ref = t.get("reference_range") or "N/A"
            flag = t.get("lab_flag") or ""
            flag_str = f"  FLAG:{flag}" if flag else ""
            lines.append(
                f"    {t.get('parameter','?')}: "
                f"{t.get('value','?')} {t.get('unit') or ''} "
                f"[Ref: {ref}]{flag_str}"
            )
    return "\n".join(lines)


def _format_analytical_summary(tests: dict) -> str:
    """
    Deterministic pre-LLM analytics layer.
    Counts normal, abnormal, high, and low parameters without any AI involvement.
    This is the 'deterministic benchmarking' component that elevates the system
    above a simple chatbot wrapper.
    """
    total       = len(tests)
    high_count  = sum(1 for t in tests.values() if t.get("status") == "High")
    low_count   = sum(1 for t in tests.values() if t.get("status") == "Low")
    normal_count= sum(1 for t in tests.values() if t.get("status") == "Normal")
    abnormal    = high_count + low_count

    return (
        f"  - Total parameters analyzed : {total}\n"
        f"  - Abnormal parameters       : {abnormal}\n"
        f"  - Parameters HIGH           : {high_count}\n"
        f"  - Parameters LOW            : {low_count}\n"
        f"  - Normal parameters         : {normal_count}"
    )


PATIENT_TASK = """
Generate the following clearly labeled sections:

1. ABNORMAL FINDINGS EXPLANATION:
   - Explain each abnormal parameter in simple, non-technical language.
   - Mention briefly why it might be relevant to health.
   - Keep tone calm, clear, and reassuring.
   - Do NOT use medical jargon without immediately explaining it.

2. OVERALL HEALTH SUMMARY:
   - Explain the overall risk level in plain language.
   - Be balanced — avoid alarmist language.
   - Acknowledge what is within normal range.

3. SUGGESTED NEXT STEPS:
   - Provide general lifestyle suggestions (diet, hydration, exercise).
   - Strongly encourage professional medical consultation.
   - Do NOT prescribe any medications.

4. EXPLAINABILITY NOTE:
   The explanation above is generated based on structured comparison of lab values
   against standard reference ranges and predefined medical knowledge context. No
   medical diagnoses have been made.

5. DISCLAIMER:
   This report explanation is generated by an AI system for informational purposes
   only. It does NOT constitute a medical diagnosis, medical advice, or a
   substitute for professional medical consultation. Always consult a qualified
   healthcare professional for any health concerns.
"""

DOCTOR_TASK = """
Generate a clinical-grade structured summary (CLINICAL MODE):

1. CLINICAL FINDINGS SUMMARY:
   - List each abnormal parameter with value, unit, and reference range deviation.
   - Use appropriate clinical terminology.
   - Note severity classification per parameter.
   - IMPORTANT: Do NOT name or label specific medical conditions or diseases.
     Instead use descriptive clinical terms:
     e.g. 'elevated glycemic levels' NOT 'diabetes' | 'low erythrocyte count' NOT 'anemia'

2. RISK STRATIFICATION:
   - Describe overall risk level with clinical context.
   - Note parameter interactions if relevant.

3. RECOMMENDED CLINICAL ACTIONS:
   - Suggest follow-up investigations based on findings.
   - Do NOT prescribe medications. Recommendation only.

4. EXPLAINABILITY NOTE:
   This summary is generated via a grounded RAG pipeline constrained to verified
   structured medical reference data. LLM output is non-diagnostic and must be
   reviewed by a licensed clinician before clinical use.

5. DISCLAIMER:
   This AI-generated clinical summary is for auxiliary decision support only.
   It does NOT replace clinical judgment. Always verify against patient history
   and current clinical guidelines.
"""


def build_prompt(
    patient_age: int,
    patient_gender: str,
    tests: dict,
    overall_risk_level: str,
    retrieved_context: str,
    mode: ModeType = "patient",
    language: LanguageType = "English",
    emergency_flag: bool = False,
    confidence_score: str = "N/A",
    trend_summary: str = None,
    patient_name: str = None,
    panels: list = None,
    dynamic_analysis: dict = None,
) -> str:
    """
    Build the complete controlled medical reasoning prompt.

    Parameters
    ----------
    patient_age        : int   — patient's age
    patient_gender     : str   — patient's gender
    tests              : dict  — raw test results dict
    overall_risk_level : str   — e.g. "Low", "Moderate", "High"
    retrieved_context  : str   — RAG-retrieved structured medical context
    mode               : str   — "patient" or "doctor"
    language           : str   — "English", "Hindi", or "Telugu"

    Returns
    -------
    str — The fully constructed prompt string, ready for Grok API call.
    """
    structured_tests      = _format_panels(panels) if panels else _format_structured_tests(tests)
    analytical_summary    = _format_analytical_summary(tests)
    task_section          = PATIENT_TASK if mode == "patient" else DOCTOR_TASK
    mode_label            = "PATIENT-FRIENDLY" if mode == "patient" else "CLINICAL (DOCTOR)"
    language_instruction  = (
        "" if language == "English"
        else f"\n\nIMPORTANT: Respond entirely in {language}. All sections must be in {language}.\n"
    )

    # Dynamic analysis summary block (from report's own reference ranges)
    dynamic_block = ""
    if dynamic_analysis and dynamic_analysis.get("analysis_summary"):
        s = dynamic_analysis["analysis_summary"]
        dynamic_block = (
            f"\n━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\n"
            f"DYNAMIC RANGE ANALYSIS (from report reference ranges)\n"
            f"━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\n"
            f"  Total tests       : {s.get('total_tests','?')}\n"
            f"  Abnormal count    : {s.get('abnormal_count','?')}\n"
            f"  Critical count    : {s.get('critical_count','?')}\n"
            f"  Dynamic risk level: {s.get('overall_risk','?')}\n"
        )

    patient_name_line = f"  Name   : {patient_name}\n" if patient_name and patient_name != "Unknown" else ""

    # UPGRADE 1: Emergency flag block (only fires on actual threshold breach)
    emergency_block = (
        "\n🚨 CRITICAL ALERT — EMERGENCY ESCALATION ACTIVE:\n"
        "One or more parameters have breached critical safety thresholds.\n"
        "IMPORTANT INSTRUCTIONS FOR THIS RESPONSE:\n"
        "  - Clearly state that immediate medical evaluation is strongly recommended.\n"
        "  - Use calm but firm language — do not catastrophize, but convey genuine urgency.\n"
        "  - Include this exact phrase: 'Immediate evaluation is strongly recommended.'\n"
        "  - Include this exact phrase: 'Delay in seeking care may increase the risk of complications.'\n"
        "  - These phrases must appear in the Suggested Next Steps section.\n"
        if emergency_flag else ""
    )

    # UPGRADE 4: Trend comparison block
    trend_block = (
        f"\n━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\n"
        f"COMPARATIVE TREND (vs Previous Report)\n"
        f"━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\n"
        f"{trend_summary}\n"
        f"Note: Mention these trends when discussing each parameter.\n"
        if trend_summary else ""
    )

    prompt = f"""You are a medical laboratory report explanation assistant operating in {mode_label} MODE.
{emergency_block}
STRICT OPERATING RULES (NON-NEGOTIABLE):
1. You are NOT a doctor and must NOT act as one.
2. You must NOT diagnose any disease or medical condition.
3. You must NOT prescribe or suggest specific medications.
4. You must NOT generate medical interpretations beyond the provided Reference Context below.
5. ONLY use the Medical Reference Context provided — do NOT invent or infer new medical facts.
6. Maintain a calm, clear, and reassuring tone throughout.
7. Avoid alarming, catastrophizing, or overly technical language (in Patient Mode).
8. Always encourage professional medical consultation when values are abnormal.
9. If asked about diagnosis directly, respond: "I cannot provide a medical diagnosis. Please consult a qualified doctor."
{language_instruction}
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
PATIENT PROFILE
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
{patient_name_line}  Age    : {patient_age} years
  Gender : {patient_gender}

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
STRUCTURED LAB RESULTS (with Reference Ranges)
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
{structured_tests}
{dynamic_block}
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
OVERALL RISK LEVEL
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
  {overall_risk_level}

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
DETERMINISTIC ANALYTICAL SUMMARY (Pre-LLM Computed)
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
{analytical_summary}
  - AI Confidence Score        : {confidence_score}
{trend_block}
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
MEDICAL REFERENCE CONTEXT (Grounded RAG — Do NOT deviate from this)
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
{retrieved_context}

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
YOUR TASK ({mode_label} MODE)
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
{task_section}
FORMAT REQUIREMENTS:
  - Use clear section headings as specified above.
  - Keep language {("simple and accessible" if mode == "patient" else "precise and clinical")}.
  - Avoid excessive length — be concise and structured.
  - Do NOT add any medical claims beyond the Reference Context provided above.
"""
    return prompt.strip()
